### PR TITLE
DomainTools Iris Investigate: Feature - Implement playbook monitoring feature

### PR DESCRIPTION
**Pull request by briluza**
Please ensure your pull request (PR) adheres to the following guidelines:

- Please refer to our contributing documentation for any questions on submitting a pull request, link: [Contribution Guide](https://github.com/splunk-soar-connectors/.github/blob/main/.github/CONTRIBUTING.md)

#### Please check if your PR fulfills the following requirements:
- [x] Testing of all the changes has been performed (for bug fixes / features)
- [x] The manual_readme_content.md has been reviewed and added / updated if needed (for bug fixes / features)
- [x] Use the following format for the PR description: `<App Name>: <PR Type> - <PR Description>`
- [x] Provide release notes as part of the PR submission which describe high level points about the changes for the upcoming GA release.
- [x] Verify all checks are passing.
- [x] Do NOT use the `next` branch of the forked repo. Create separate feature branch for raising the PR.
- [x] Do NOT submit updates to dependencies unless it fixes an issue.
#### Please check the type of change your PR introduces:
- [ ] New App
- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [x] Documentation
- [ ] Other (please describe):

## Security Considerations (REQUIRED)
- [ ] If you are exposing any endpoints using a [REST handler](https://docs.splunk.com/Documentation/SOAR/current/DevelopApps/RESTHandlers),
  please document them in the `manual_readme_content.md`.
- [x] If this is a new connector or you are adding new actions
    - [x] Please document in the `manual_readme_content.md` all methods (eg, OAuth) used to authenticate
      with the service that the connector is integrating with.
    - [ ] If any actions are unable to run on SOAR Cloud, please document this in the `manual_readme_content.md`.
- [ ] Are you introducing any new cryptography modules? If yes, please elaborate their purpose:
- [ ] Are you are accessing the file system? If yes, please verify that you are only accessing paths returned through
the [Vault](https://docs.splunk.com/Documentation/SOARonprem/5.2.1/DevelopApps/AppDevAPIRef#Vault) API.
- [ ] Are you are marking code to be ignored by Semgrep with [`nosemgrep`](https://semgrep.dev/docs/ignoring-files-folders-code/#ignoring-code-through-nosemgrep)?
If yes, please provide justification in an additional comment next to the ignored code.

## Release Notes (REQUIRED)
- Provide release notes as part of the PR submission which describe high level points about the changes for the upcoming GA release.

## What is the current behavior? (OPTIONAL)
- Describe the current behavior that you are modifying.

## What is the new behavior? (OPTIONAL)
- Describe the behavior or changes that are being added by this PR.

## Other information (OPTIONAL)
- Any other information that is important to this PR such as screenshots of how the component looks before and after the change.

## Pay close attention to (OPTIONAL)
- Any specific code change or test case points which must be addressed/reviewed at the time of GA release.

## Screenshots (if relevant)
image

---
Thanks for contributing!

### CODE REVIEW

**Comment by mmomin-crest** [comment]
Hello @briluza, Could you please grant the right access to me for performing the commit and push operations?

**Comment by wesleya** [comment]
Hi @mmomin-crest, I've given you write access to this repo. You should have permission for commit and push operations. Please let us know if you have any trouble with that. Thank you!

**Comment by mmomin-crest** [comment]
> Hi @mmomin-crest, I've given you write access to this repo. You should have permission for commit and push operations. Please let us know if you have any trouble with that. Thank you!

Thanks! Stil I am facing issue while pushing the changes to branch '1.5.0'. Can you please check once. 

image

FYI - As per our practice, I have removed the requests and their sub dependencies. Now we only use requests and their dependencies from Splunk SOAR Platform.

**Comment by wesleya** [comment]
@mmomin-crest github is showing your access to the repo as `Pending Invite - Awaiting mmomin-crest’s response`. Maybe the last invite was expired or caught in junk so I've gone ahead and re-added you. Let me know if you don't see the invite, thank you!

**Comment by mmomin-crest** [comment]
> @mmomin-crest github is showing your access to the repo as `Pending Invite - Awaiting mmomin-crest’s response`. Maybe the last invite was expired or caught in junk so I've gone ahead and re-added you. Let me know if you don't see the invite, thank you!

Okay, I got the invite and accepted it. Now, able to push the changes.

**Review by dnunes-domaintools — APPROVED** [review]

**Comment by dnunes-domaintools** [comment]
Thanks for your help with this, @mmomin-crest ! Seeing as we seem to face the linting test failures on each of the past few submissions we've made to this repo, is there anything we should be doing differently, or anything to be fixed in the automation so we don't have to get you involved on each push we make? (you can also reach the team here directly at integrations@domaintools.com)

**Pull request merged**
